# Generated by Django 3.1.4 on 2020-12-23 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oscabecalho',
            options={'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AddField(
            model_name='oscabecalho',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oscabecalho',
            name='referencia',
            field=models.CharField(max_length=20, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='oscabecalho',
            name='servico',
            field=models.CharField(max_length=20, verbose_name='Serviço'),
        ),
    ]
