# Generated by Django 3.1.4 on 2020-12-23 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0003_oscabecalho_dtpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='oscabecalho',
            name='numero',
            field=models.CharField(default=823, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oscabecalho',
            name='dtpedido',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data do Pedido'),
        ),
    ]
