# Generated by Django 3.1.4 on 2020-12-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0004_auto_20201223_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscabecalho',
            name='uf',
            field=models.CharField(choices=[('MG', 'Minas Gerais'), ('SP', 'São Paulo')], max_length=2),
        ),
    ]
